name: Continuous Integration

on:
    release:
        types: [published]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Update dependencies
              run: composer update --no-progress

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run test suites
              run: composer run-script test
